cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - reports/

stages:
  - install
  - test
  - codequality
  - cleanup

prepend:
  stage: install
  script:
    - mkdir -p ./reports
  tags:
    - bash

composer:
  stage: install
  script:
    - php7.4 /usr/bin/composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  tags:
    - bash

lint:
  stage: test
  script:
    - php7.4 vendor/bin/phplint ./app --xml=reports/lint.xml
  dependencies:
    - composer
  artifacts:
    when: always
    reports:
      junit: reports/lint.xml
  tags:
    - bash

codestyle:
  stage: codequality
  script:
    - php7.4 vendor/bin/phpcs -p --standard=PSR12 --report=junit --report-file=reports/checkstyle.xml ./app
  dependencies:
    - composer
  artifacts:
    when: always
    reports:
      junit: reports/checkstyle.xml
  tags:
    - bash

codequality:
  stage: codequality
  script:
    - php7.4 vendor/bin/phpmd ./app text cleancode,codesize,controversial,design,naming,unusedcode --reportfile reports/phpmd.txt  --ignore-violations-on-exit
  dependencies:
    - composer
  artifacts:
    when: always
    paths:
      - reports
  tags:
    - bash

duplicatedcode:
  stage: codequality
  script:
    - php7.4 vendor/bin/phpcpd ./app --log-pmd=reports/phpcpd.xml
  dependencies:
    - composer
  artifacts:
    when: always
    paths:
      - reports
  tags:
    - bash


phpunit:
  stage: test
  script:
    - php7.4 vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text
  dependencies:
    - composer
  artifacts:
    paths:
      - reports
    reports:
      junit: reports/junit.xml
  tags:
    - bash

pages:
  stage: cleanup
  script:
    - mkdir -p public
    - cp -r reports/* public/
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - bash
