cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - reports/

variables:
  PHP_COMPOSER: 'php7.4 /usr/bin/composer'

stages:
  - install
  - test
  - codequality
  - cleanup

prepend:
  stage: install
  script:
    - mkdir -p ./reports
  tags:
    - bash

composer:
  stage: install
  script:
    - $PHP_COMPOSER install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  tags:
    - bash

lint:
  stage: test
  script:
    - $PHP_COMPOSER php-lint
  dependencies:
    - composer
  artifacts:
    when: always
    reports:
      junit: reports/lint.xml
  tags:
    - bash

codestyle:
  stage: codequality
  script:
    - $PHP_COMPOSER php-cs
  dependencies:
    - composer
  artifacts:
    when: always
    reports:
      junit: reports/checkstyle.xml
  tags:
    - bash

codequality:
  stage: codequality
  script:
    - $PHP_COMPOSER php-md
  dependencies:
    - composer
  artifacts:
    when: always
    paths:
      - reports
  tags:
    - bash

duplicatedcode:
  stage: codequality
  script:
    - $PHP_COMPOSER php-cpd
  dependencies:
    - composer
  artifacts:
    when: always
    paths:
      - reports
  tags:
    - bash


phpunit:
  stage: test
  script:
    - $PHP_COMPOSER php-unit
  dependencies:
    - composer
  artifacts:
    paths:
      - reports
    reports:
      junit: reports/junit.xml
  tags:
    - bash

pages:
  stage: cleanup
  script:
    - mkdir public
    - cp -r reports/* public/
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - bash
