version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./resources/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sandbox-network

  php:
    image: php:rc-fpm
    volumes:
      - .:/www
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge
